### ISSUE TITLE
Wrong Net payable amount showing up after generating the payslip. 

### ISSUE THREAD

**Issue by devendarreddy-dev** [SaddaHaq/SH_EMP#17]
After choosing Leaves & amount  generate payslip.
![image](https://cloud.githubusercontent.com/assets/7886799/5626565/2d1a6146-95b3-11e4-95f6-ef50e8711244.png)

After Genarating payslip.See it showing full pay for Net payable amount.
![image](https://cloud.githubusercontent.com/assets/7886799/5626574/43f0d6de-95b3-11e4-98df-36b677c67248.png)

**Comment by satishkumarmukkoju** [comment]
the amount showing after deductions.

**Comment by devendarreddy-dev** [comment]
Once again Check the issue properly
