### ISSUE TITLE
I'm able to edit 'Net payable' amount directly after completed the paid process.

### ISSUE THREAD

**Issue by devendarreddy-dev** [SaddaHaq/SH_EMP#18]
![image](https://cloud.githubusercontent.com/assets/7886799/5626697/fcf93b02-95b4-11e4-81f4-a35789830c98.png)

**Comment by satishkumarmukkoju** [comment]
Nothing happen if you edit that thing

**Comment by devendarreddy-dev** [comment]
Yes. But we are providing the Revert option to edit all those things.. So try to enable that thing while reverting but not at paid status(Disable that option like 'max payable & leaves when paid status is completed).
