### ISSUE TITLE
Show leave dates(from & to dates) to HR & Manager.

### ISSUE THREAD

**Issue by devendarreddy-dev** [SaddaHaq/SH_EMP#22]
You are displaying only applied date not leave dates. 
![image](https://cloud.githubusercontent.com/assets/7886799/5642301/fca60fc8-966c-11e4-89c0-88af9cf074cf.png)

**Comment by devendarreddy-dev** [comment]
As well as provide to employee.

**Comment by satishkumarmukkoju** [comment]
issue fixed please check once
